import { slugify } from "../engine/recipe";
import type { LlmSettings, Recipe } from "../engine/types";
import { scriptJson } from "./html";

// A recipe as an MCP tool. Two flavours share one JSON-RPC handler:
//  - a single .mjs file for Claude Desktop / Claude Code (stdio, no dependencies)
//  - a Cloudflare Worker (Streamable HTTP, protected by a Bearer token)

const OVH = {
  base: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
  model: "Mistral-Small-3.2-24B-Instruct-2506",
};

export function mcpToolName(recipe: Recipe) {
  return slugify(recipe.title).replace(/-/g, "_").slice(0, 60) || "langplay_recipe";
}

function defaults(settings?: LlmSettings) {
  const keyed =
    settings && !["simulator", "pollinations", "ovh", "puter", "horde"].includes(settings.provider);
  return keyed
    ? { base: settings.baseUrl, model: settings.model, keyed: true }
    : { ...OVH, keyed: false };
}

/** JSON-RPC handler source, shared by both flavours. Expects `Langplay`, `RECIPE`, `settings()`. */
function handlerSource(recipe: Recipe): string {
  const tool = {
    name: mcpToolName(recipe),
    description:
      `${recipe.title}: ${recipe.summary} (A Langplay recipe with ${recipe.nodes.length} steps.)`.slice(
        0,
        1000,
      ),
    inputSchema: {
      type: "object",
      properties: {
        question: {
          type: "string",
          description: "The question or request to run through the recipe.",
        },
        documents: {
          type: "array",
          description: "Optional documents for Document Lookup steps.",
          items: {
            type: "object",
            properties: { name: { type: "string" }, text: { type: "string" } },
            required: ["text"],
          },
        },
        show_steps: { type: "boolean", description: "Include what each step did." },
      },
      required: ["question"],
    },
  };
  return `const TOOL = ${scriptJson(tool)};
const SERVER = { name: ${JSON.stringify(`langplay-${slugify(recipe.title)}`)}, version: "1.0.0" };

async function runTool(args) {
  const question = String(args?.question || "").slice(0, 8000);
  if (!question.trim()) throw new Error("question is required");
  const s = settings();
  let chunks = [];
  for (const d of Array.isArray(args?.documents) ? args.documents.slice(0, 20) : [])
    chunks = chunks.concat(Langplay.chunkPages(String(d.name || "document"), Langplay.textToPages(String(d.text || ""))));
  const result = await Langplay.runRecipe(RECIPE, question, {
    chat: Langplay.createChat(s),
    fallbackChat: Langplay.simulatorChat,
    searchDocs: chunks.length ? (q, k) => Langplay.searchChunks(chunks, q, k) : undefined,
  });
  let text = result.answer;
  if (args?.show_steps)
    text += "\\n\\n---\\nSteps:\\n" + result.steps.map((st) => "- " + st.label + (st.decision ? " (" + st.decision + ")" : "") + (st.note ? " [" + st.note + "]" : "") + ": " + st.output.slice(0, 400).replace(/\\n/g, " ")).join("\\n");
  return text;
}

async function handle(msg) {
  if (!msg || msg.jsonrpc !== "2.0" || typeof msg.method !== "string") {
    return msg && msg.id !== undefined ? { jsonrpc: "2.0", id: msg.id, error: { code: -32600, message: "Invalid request" } } : null;
  }
  const reply = (result) => ({ jsonrpc: "2.0", id: msg.id, result });
  if (msg.id === undefined || msg.id === null) return null; // notification
  switch (msg.method) {
    case "initialize":
      return reply({ protocolVersion: msg.params?.protocolVersion || "2025-06-18", capabilities: { tools: {} }, serverInfo: SERVER });
    case "ping":
      return reply({});
    case "tools/list":
      return reply({ tools: [TOOL] });
    case "tools/call":
      if (msg.params?.name !== TOOL.name)
        return { jsonrpc: "2.0", id: msg.id, error: { code: -32602, message: "Unknown tool: " + msg.params?.name } };
      try {
        return reply({ content: [{ type: "text", text: await runTool(msg.params.arguments || {}) }] });
      } catch (error) {
        return reply({ content: [{ type: "text", text: "Error: " + (error?.message || error) }], isError: true });
      }
    default:
      return { jsonrpc: "2.0", id: msg.id, error: { code: -32601, message: "Method not found: " + msg.method } };
  }
}
`;
}

function recipeSource(recipe: Recipe) {
  const { id: _id, spinout: _s, ...clean } = recipe;
  return `const RECIPE = ${scriptJson(clean)};`;
}

export function mcpStdioScript(recipe: Recipe, engineJs: string, settings?: LlmSettings): string {
  const d = defaults(settings);
  const file = `${slugify(recipe.title)}-mcp.mjs`;
  return `#!/usr/bin/env node
// ${recipe.title} — an MCP server generated by Langplay. One file, no dependencies, Node 20+.
//
// Claude Desktop: Settings → Developer → Edit Config, then add:
//   "mcpServers": { ${JSON.stringify(slugify(recipe.title))}: { "command": "node", "args": ["C:/path/to/${file}"] } }
// Claude Code:  claude mcp add ${slugify(recipe.title)} -- node /path/to/${file}
//
// AI service: ${d.keyed ? "set LANGPLAY_API_KEY (keys are never exported)." : "OVHcloud's free endpoint by default (about 2 requests a minute, no key)."}
// Override with LANGPLAY_BASE_URL, LANGPLAY_MODEL and LANGPLAY_API_KEY (any OpenAI-compatible service).

${engineJs}
${recipeSource(recipe)}
function settings() {
  const env = process.env;
  return {
    provider: env.LANGPLAY_API_KEY ? "custom" : ${JSON.stringify(d.keyed ? "custom" : "ovh")},
    baseUrl: env.LANGPLAY_BASE_URL || ${JSON.stringify(d.base)},
    model: env.LANGPLAY_MODEL || ${JSON.stringify(d.model)},
    apiKey: env.LANGPLAY_API_KEY || "",
  };
}
${handlerSource(recipe)}
// stdio transport: one JSON-RPC message per line; logs go to stderr only.
let buffer = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (chunk) => {
  buffer += chunk;
  let nl;
  while ((nl = buffer.indexOf("\\n")) >= 0) {
    const line = buffer.slice(0, nl).trim();
    buffer = buffer.slice(nl + 1);
    if (!line) continue;
    let msg;
    try { msg = JSON.parse(line); } catch {
      process.stdout.write(JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } }) + "\\n");
      continue;
    }
    Promise.resolve(handle(msg)).then((out) => { if (out) process.stdout.write(JSON.stringify(out) + "\\n"); });
  }
});
process.stdin.on("end", () => process.exit(0));
console.error("Langplay MCP server ready: " + TOOL.name);
`;
}

export function mcpWorker(
  recipe: Recipe,
  engineJs: string,
  settings?: LlmSettings,
): { worker: string; wrangler: string; readme: string } {
  const d = defaults(settings);
  const name = `${slugify(recipe.title)}-mcp`.slice(0, 54);
  const worker = `// ${recipe.title} — a remote MCP server (Streamable HTTP) generated by Langplay for Cloudflare Workers.
// Every request needs "Authorization: Bearer <LANGPLAY_TOKEN>" — set it with: wrangler secret put LANGPLAY_TOKEN

${engineJs}
${recipeSource(recipe)}
let ENV = {};
function settings() {
  return {
    provider: ENV.LANGPLAY_API_KEY ? "custom" : ${JSON.stringify(d.keyed ? "custom" : "ovh")},
    baseUrl: ENV.LANGPLAY_BASE_URL || ${JSON.stringify(d.base)},
    model: ENV.LANGPLAY_MODEL || ${JSON.stringify(d.model)},
    apiKey: ENV.LANGPLAY_API_KEY || "",
  };
}
${handlerSource(recipe)}
function safeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

export default {
  async fetch(request, env) {
    ENV = env;
    const json = (body, status = 200) => new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });
    if (!env.LANGPLAY_TOKEN) return json({ error: "Server not configured: set the LANGPLAY_TOKEN secret." }, 500);
    const auth = request.headers.get("Authorization") || "";
    if (!safeEqual(auth, "Bearer " + env.LANGPLAY_TOKEN)) return json({ error: "Unauthorized" }, 401);
    if (request.method !== "POST") return json({ error: "POST JSON-RPC messages to this URL." }, 405);
    let body;
    try { body = await request.json(); } catch { return json({ jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } }, 400); }
    if (Array.isArray(body)) {
      const out = (await Promise.all(body.slice(0, 20).map(handle))).filter(Boolean);
      return out.length ? json(out) : new Response(null, { status: 202 });
    }
    const out = await handle(body);
    return out ? json(out) : new Response(null, { status: 202 });
  },
};
`;
  const wrangler = `name = "${name}"
main = "worker.mjs"
compatibility_date = "2026-10-01"

[vars]
LANGPLAY_BASE_URL = "${d.base}"
LANGPLAY_MODEL = "${d.model}"

# Secrets (never put them in this file):
#   npx wrangler secret put LANGPLAY_TOKEN     <- the password Claude will send
#   npx wrangler secret put LANGPLAY_API_KEY   <- only if your AI service needs a key
`;
  const readme = `# ${recipe.title} — remote MCP server

Generated by Langplay. Runs the recipe on Cloudflare Workers so Claude (or any MCP client) can call it as a tool.

1. Install Node 20+, then in this folder: \`npx wrangler login\`
2. Choose a long random password and run \`npx wrangler secret put LANGPLAY_TOKEN\`
3. \`npx wrangler deploy\` — note the URL it prints.
4. Add it to your MCP client as a remote (HTTP) server with header \`Authorization: Bearer <your password>\`.

Requests without the password get 401. The free AI endpoint is rate-limited (about 2 requests a minute);
set \`LANGPLAY_BASE_URL\`, \`LANGPLAY_MODEL\` and the \`LANGPLAY_API_KEY\` secret for your own service.
`;
  return { worker, wrangler, readme };
}
